# (theme, line, photo)  — photos are the venue's own posted carousels
A="myard_DbtHqqojY8c_%02d.jpg"; B="myard_DbldAuODb54_%02d.jpg"
C="myard_DbdbdRaCDVq_%02d.jpg"; D="myard_DbVYg0TjT6a_%02d.jpg"; E="myard_DbIPfH8jXp9_%02d.jpg"
LINES=[
("The place","kinda chic to have a hidden courtyard as your local",B%2,"paul"),
("The place","kinda chic to know where the yard is",D%3,"paul"),
("The place","kinda chic to have somewhere that's yours in town",B%2,""),
("The place","kinda chic that the roof is just the sky",B%2,""),
("The place","kinda chic to be the one who found it first",A%5,""),
("The place","kinda chic to give directions nobody else can",D%3,""),
("After work","kinda chic to go for one after work and stay all night",A%2,"paul"),
("After work","kinda chic that one drink turned into five",B%1,""),
("After work","kinda chic to come straight from work",E%7,""),
("After work","kinda chic to cancel the rest of your evening",A%2,""),
("After work","kinda chic that friday starts at five",E%3,""),
("After work","kinda chic to have nowhere else to be",E%5,""),
("Music","kinda chic to know every word when the dj plays that song",D%4,"paul"),
("Music","kinda chic to hear the sax before you see it",B%5,""),
("Music","kinda chic to have live sax with your second drink",B%5,""),
("Music","kinda chic when the dj plays it anyway",B%3,""),
("Music","kinda chic to dance where there is no dancefloor",A%4,""),
("Music","kinda chic when you can still hear each other",B%1,""),
("Music","kinda chic to lose an hour to one song",E%6,""),
("Drinks","kinda chic to match your drink to your bag",C%3,""),
("Drinks","kinda chic to order the one with the orange on it",C%4,""),
("Drinks","kinda chic to watch them build it in front of you",C%4,""),
("Drinks","kinda chic to know your order before you get there",C%1,""),
("Drinks","kinda chic to drink something frozen in leicester",C%3,""),
("Drinks","kinda chic to hold a proper glass outdoors",C%2,""),
("Drinks","kinda chic when the pint catches the light",C%5,""),
("Drinks","kinda chic to let them choose for you",C%1,""),
("Drinks","kinda chic to never look at the menu",C%6,""),
("People","kinda chic to make friends with the table next to you",A%3,"paul"),
("People","kinda chic to arrive as two and leave as nine",A%5,""),
("People","kinda chic to be on first name terms with the bar",B%4,""),
("People","kinda chic that nobody asks what you do for a living",E%2,""),
("People","kinda chic to bring your mum and your mates",E%2,""),
("People","kinda chic that every table is the best table",E%5,""),
("People","kinda chic to laugh at nothing for a full minute",A%2,""),
("People","kinda chic to share a bench with strangers",A%3,""),
("People","kinda chic to hug someone you met at the bar",D%1,""),
("People","kinda chic to be the loudest table and the nicest",E%3,""),
("Sun","kinda chic to spend your weekends outside",A%5,"paul"),
("Sun","kinda chic to get a tan line at the bar",A%5,""),
("Sun","kinda chic to move tables as the sun moves",A%3,""),
("Sun","kinda chic to sit outside in leicester and mean it",D%5,""),
("Sun","kinda chic to watch it get dark from outside",B%2,""),
("Staff","kinda chic when the staff are having more fun",B%4,""),
("Staff","kinda chic that they know your face",B%4,""),
("The neon","kinda chic to be hotter than your ex",D%3,""),
("The neon","kinda chic to always pose under the same neon",D%3,""),
("Getting ready","kinda chic to dress up for a picnic bench",A%1,""),
("Getting ready","kinda chic to wear white and risk it",A%1,""),
("Getting ready","kinda chic to get ready for a courtyard",D%5,""),
("Regulars","kinda chic to be someone's favourite regular",E%4,""),
("Regulars","kinda chic to still be here at closing",E%2,""),
]
